// Generated by scripts/generate-english-content-audio.ts. Do not edit by hand.
// Paths are downloaded on demand so recordings do not inflate the mobile binary.
const contentAudio: Record<string, string> = {
  "en-US:Hello!": "en-US/en-phrase-1.mp3",
  "en-US:My name is ___.": "en-US/en-phrase-2.mp3",
  "en-US:I would like water, please.": "en-US/en-phrase-3.mp3",
  "en-US:hello": "en-US/en-vocabulary-hello.mp3",
  "en-US:water": "en-US/en-vocabulary-water.mp3",
  "en-US:book": "en-US/en-vocabulary-book.mp3",
  "en-US:sun": "en-US/en-vocabulary-sun.mp3",
  "en-US:cat": "en-US/en-vocabulary-cat.mp3",
  "en-US:house": "en-US/en-vocabulary-house.mp3",
  "en-GB:Hello!": "en-GB/en-phrase-1.mp3",
  "en-GB:My name is ___.": "en-GB/en-phrase-2.mp3",
  "en-GB:I would like water, please.": "en-GB/en-phrase-3.mp3",
  "en-GB:hello": "en-GB/en-vocabulary-hello.mp3",
  "en-GB:water": "en-GB/en-vocabulary-water.mp3",
  "en-GB:book": "en-GB/en-vocabulary-book.mp3",
  "en-GB:sun": "en-GB/en-vocabulary-sun.mp3",
  "en-GB:cat": "en-GB/en-vocabulary-cat.mp3",
  "en-GB:house": "en-GB/en-vocabulary-house.mp3",
};

export function getEnglishContentAudioPath(text: string, pronunciationVariantId: string): string | null {
  return contentAudio[`${pronunciationVariantId}:${text.trim()}`] ?? null;
}

export const englishContentRecordingCount = 18;
