import type { AudioSource } from 'expo-audio';

// Generated by scripts/generate-english-content-audio.ts. Do not edit by hand.
const contentAudio: Record<string, AudioSource> = {
  "en-US:Hello!": require('../../assets/audio/en-US/en-phrase-1.mp3'),
  "en-US:My name is ___.": require('../../assets/audio/en-US/en-phrase-2.mp3'),
  "en-US:I would like water, please.": require('../../assets/audio/en-US/en-phrase-3.mp3'),
  "en-US:hello": require('../../assets/audio/en-US/en-vocabulary-hello.mp3'),
  "en-US:water": require('../../assets/audio/en-US/en-vocabulary-water.mp3'),
  "en-US:book": require('../../assets/audio/en-US/en-vocabulary-book.mp3'),
  "en-US:sun": require('../../assets/audio/en-US/en-vocabulary-sun.mp3'),
  "en-US:cat": require('../../assets/audio/en-US/en-vocabulary-cat.mp3'),
  "en-US:house": require('../../assets/audio/en-US/en-vocabulary-house.mp3'),
  "en-GB:Hello!": require('../../assets/audio/en-GB/en-phrase-1.mp3'),
  "en-GB:My name is ___.": require('../../assets/audio/en-GB/en-phrase-2.mp3'),
  "en-GB:I would like water, please.": require('../../assets/audio/en-GB/en-phrase-3.mp3'),
  "en-GB:hello": require('../../assets/audio/en-GB/en-vocabulary-hello.mp3'),
  "en-GB:water": require('../../assets/audio/en-GB/en-vocabulary-water.mp3'),
  "en-GB:book": require('../../assets/audio/en-GB/en-vocabulary-book.mp3'),
  "en-GB:sun": require('../../assets/audio/en-GB/en-vocabulary-sun.mp3'),
  "en-GB:cat": require('../../assets/audio/en-GB/en-vocabulary-cat.mp3'),
  "en-GB:house": require('../../assets/audio/en-GB/en-vocabulary-house.mp3'),
};

export function getEnglishContentAudio(text: string, pronunciationVariantId: string): AudioSource | null {
  return contentAudio[`${pronunciationVariantId}:${text.trim()}`] ?? null;
}

export const englishContentRecordingCount = 18;
