import type { AudioSource } from 'expo-audio';

// Generated by scripts/generate-gemini-marathi-audio.ts. Do not edit by hand.
const unitAudio: Record<string, AudioSource> = {
  "mr-vowels-1-1": require('../../assets/audio/mr-IN/mr-vowels-1-1.wav'),
};
const textAudio: Record<string, AudioSource> = {

};

export function getMarathiUnitAudio(unitId: string): AudioSource | null {
  return unitAudio[unitId] ?? null;
}

export function getMarathiTextAudio(text: string): AudioSource | null {
  return textAudio[text.trim()] ?? null;
}

export const marathiRecordingCount = 1;
