import type { PhraseEntry } from '@/models';

export const phrasebook: Record<string, PhraseEntry[]> = {
  en: [
    { native: 'Hello!', romanization: 'hello', english: 'Hello!' },
    { native: 'My name is ___.', romanization: 'my name is', english: 'My name is ___.' },
    { native: 'I would like water, please.', romanization: 'I would like water, please', english: 'I would like water, please.' },
  ],
  mr: [
    { native: 'नमस्कार!', romanization: 'namaskār', english: 'Hello!' },
    { native: 'माझे नाव ___ आहे.', romanization: 'mājhe nāv ___ āhe', english: 'My name is ___.' },
    { native: 'तुमचे नाव काय आहे?', romanization: 'tumce nāv kāy āhe', english: 'What is your name?' },
    { native: 'तुम्ही कसे आहात?', romanization: 'tumhī kase āhāt', english: 'How are you?' },
    { native: 'मी ठीक आहे.', romanization: 'mī ṭhīk āhe', english: 'I am fine.' },
    { native: 'हो.', romanization: 'ho', english: 'Yes.' },
    { native: 'नाही.', romanization: 'nāhī', english: 'No.' },
    { native: 'मला मराठी शिकायची आहे.', romanization: 'malā marāṭhī śikāyacī āhe', english: 'I want to learn Marathi.' },
    { native: 'कृपया हळू बोला.', romanization: 'kr̥payā haḷū bolā', english: 'Please speak slowly.' },
    { native: 'पुन्हा सांगा, कृपया.', romanization: 'punhā sāṅgā, kr̥payā', english: 'Please say it again.' },
    { native: 'मला समजले.', romanization: 'malā samajale', english: 'I understood.' },
    { native: 'मला समजले नाही.', romanization: 'malā samajale nāhī', english: 'I did not understand.' },
    { native: 'मला पाणी हवे आहे.', romanization: 'malā pāṇī have āhe', english: 'I would like water.' },
    { native: 'धन्यवाद!', romanization: 'dhanyavād', english: 'Thank you!' },
    { native: 'पुन्हा भेटूया.', romanization: 'punhā bheṭūyā', english: 'See you again.' },
  ],
  hi: [
    { native: 'नमस्ते!', romanization: 'namaste', english: 'Hello!' },
    { native: 'मेरा नाम ___ है।', romanization: 'merā nām ___ hai', english: 'My name is ___.' },
    { native: 'मुझे पानी चाहिए।', romanization: 'mujhe pānī chāhiye', english: 'I would like water.' },
    { native: 'आपका नाम क्या है?', romanization: 'āpkā nām kyā hai', english: 'What is your name?' },
    { native: 'आप कैसे हैं?', romanization: 'āp kaise haiṃ', english: 'How are you?' },
    { native: 'मैं ठीक हूँ।', romanization: 'maiṃ ṭhīk hūṃ', english: 'I am fine.' },
    { native: 'हाँ।', romanization: 'hā̃', english: 'Yes.' },
    { native: 'नहीं।', romanization: 'nahīṃ', english: 'No.' },
    { native: 'कृपया धीरे बोलिए।', romanization: 'kṛpayā dhīre bolie', english: 'Please speak slowly.' },
    { native: 'धन्यवाद!', romanization: 'dhanyavād', english: 'Thank you!' },
    { native: 'अलविदा!', romanization: 'alvidā', english: 'Goodbye!' },
  ],
  fr: [
    { native: 'Bonjour !', romanization: 'bohn-zhoor', english: 'Hello!' },
    { native: "Je m’appelle ___.", romanization: 'zhuh mah-pell', english: 'My name is ___.' },
    { native: "Je voudrais de l’eau, s’il vous plaît.", romanization: 'zhuh voo-dray duh loh', english: 'I would like water, please.' },
    { native: 'Comment vous appelez-vous ?', romanization: 'koh-mahn voo zah-play voo', english: 'What is your name?' },
    { native: 'Comment allez-vous ?', romanization: 'koh-mahn tah-lay voo', english: 'How are you?' },
    { native: 'Je vais bien.', romanization: 'zhuh vay byan', english: 'I am fine.' },
    { native: 'Oui.', romanization: 'wee', english: 'Yes.' },
    { native: 'Non.', romanization: 'nohn', english: 'No.' },
    { native: 'Parlez lentement, s’il vous plaît.', romanization: 'par-lay lahn-tuh-mahn', english: 'Please speak slowly.' },
    { native: 'Merci !', romanization: 'mehr-see', english: 'Thank you!' },
    { native: 'Au revoir !', romanization: 'oh ruh-vwahr', english: 'Goodbye!' },
  ],
  es: [
    { native: '¡Hola!', romanization: 'oh-la', english: 'Hello!' },
    { native: 'Me llamo ___.', romanization: 'meh yah-moh', english: 'My name is ___.' },
    { native: 'Quisiera agua, por favor.', romanization: 'kee-syeh-rah ah-gwah', english: 'I would like water, please.' },
    { native: '¿Cómo te llamas?', romanization: 'koh-moh teh yah-mahs', english: 'What is your name?' },
    { native: '¿Cómo estás?', romanization: 'koh-moh ehs-tahs', english: 'How are you?' },
    { native: 'Estoy bien.', romanization: 'ehs-toy byehn', english: 'I am fine.' },
    { native: 'Sí.', romanization: 'see', english: 'Yes.' },
    { native: 'No.', romanization: 'noh', english: 'No.' },
    { native: 'Habla despacio, por favor.', romanization: 'ah-blah dehs-pah-syoh', english: 'Please speak slowly.' },
    { native: '¡Gracias!', romanization: 'grah-syahs', english: 'Thank you!' },
    { native: '¡Adiós!', romanization: 'ah-dyohs', english: 'Goodbye!' },
  ],
  it: [
    { native: 'Ciao!', romanization: 'chow', english: 'Hello!' },
    { native: 'Mi chiamo ___.', romanization: 'mee kyah-moh', english: 'My name is ___.' },
    { native: "Vorrei dell’acqua, per favore.", romanization: 'vor-ray dell ah-kwah', english: 'I would like water, please.' },
    { native: 'Come ti chiami?', romanization: 'koh-meh tee kyah-mee', english: 'What is your name?' },
    { native: 'Come stai?', romanization: 'koh-meh stai', english: 'How are you?' },
    { native: 'Sto bene.', romanization: 'stoh beh-neh', english: 'I am fine.' },
    { native: 'Sì.', romanization: 'see', english: 'Yes.' },
    { native: 'No.', romanization: 'noh', english: 'No.' },
    { native: 'Parla lentamente, per favore.', romanization: 'par-lah len-tah-men-teh', english: 'Please speak slowly.' },
    { native: 'Grazie!', romanization: 'grah-tsyeh', english: 'Thank you!' },
    { native: 'Arrivederci!', romanization: 'ar-ree-veh-der-chee', english: 'Goodbye!' },
  ],
  de: [
    { native: 'Hallo!', romanization: 'hah-loh', english: 'Hello!' },
    { native: 'Ich heiße ___.', romanization: 'ikh high-seh', english: 'My name is ___.' },
    { native: 'Ich möchte Wasser, bitte.', romanization: 'ikh merkh-teh vah-ser', english: 'I would like water, please.' },
    { native: 'Wie heißt du?', romanization: 'vee hyst doo', english: 'What is your name?' },
    { native: 'Wie geht es dir?', romanization: 'vee gate es deer', english: 'How are you?' },
    { native: 'Mir geht es gut.', romanization: 'meer gate es goot', english: 'I am fine.' },
    { native: 'Ja.', romanization: 'yah', english: 'Yes.' },
    { native: 'Nein.', romanization: 'nine', english: 'No.' },
    { native: 'Bitte sprich langsam.', romanization: 'bit-teh shprikh lahng-zahm', english: 'Please speak slowly.' },
    { native: 'Danke!', romanization: 'dahn-keh', english: 'Thank you!' },
    { native: 'Auf Wiedersehen!', romanization: 'owf vee-der-zay-en', english: 'Goodbye!' },
  ],
  ru: [
    { native: 'Здравствуйте!', romanization: 'zdravstvuyte', english: 'Hello!' },
    { native: 'Меня зовут ___.', romanization: 'menya zovut', english: 'My name is ___.' },
    { native: 'Я хочу воды, пожалуйста.', romanization: 'ya khochu vody, pozhaluysta', english: 'I would like water, please.' },
    { native: 'Как вас зовут?', romanization: 'kak vas zovut', english: 'What is your name?' },
    { native: 'Как дела?', romanization: 'kak dela', english: 'How are you?' },
    { native: 'У меня всё хорошо.', romanization: 'u menya vsyo khorosho', english: 'I am fine.' },
    { native: 'Да.', romanization: 'da', english: 'Yes.' },
    { native: 'Нет.', romanization: 'nyet', english: 'No.' },
    { native: 'Говорите медленнее, пожалуйста.', romanization: 'govorite medlenneye, pozhaluysta', english: 'Please speak slowly.' },
    { native: 'Спасибо!', romanization: 'spasibo', english: 'Thank you!' },
    { native: 'До свидания!', romanization: 'do svidaniya', english: 'Goodbye!' },
  ],
  ar: [
    { native: 'مرحبًا!', romanization: 'marḥaban', english: 'Hello!' },
    { native: 'اسمي ___.', romanization: 'ismī ___', english: 'My name is ___.' },
    { native: 'أريد ماءً، من فضلك.', romanization: 'urīdu māʾan, min faḍlik', english: 'I would like water, please.' },
    { native: 'ما اسمك؟', romanization: 'mā ismuk', english: 'What is your name?' },
    { native: 'كيف حالك؟', romanization: 'kayfa ḥāluk', english: 'How are you?' },
    { native: 'أنا بخير.', romanization: 'anā bikhayr', english: 'I am fine.' },
    { native: 'نعم.', romanization: 'naʿam', english: 'Yes.' },
    { native: 'لا.', romanization: 'lā', english: 'No.' },
    { native: 'تكلم ببطء، من فضلك.', romanization: 'takallam bibuṭʾ, min faḍlik', english: 'Please speak slowly.' },
    { native: 'شكرًا!', romanization: 'shukran', english: 'Thank you!' },
    { native: 'إلى اللقاء!', romanization: 'ilā al-liqāʾ', english: 'Goodbye!' },
  ],
  zh: [
    { native: '你好！', romanization: 'nǐ hǎo', english: 'Hello!' },
    { native: '我叫___。', romanization: 'wǒ jiào ___', english: 'My name is ___.' },
    { native: '我想要水，谢谢。', romanization: 'wǒ xiǎng yào shuǐ, xièxie', english: 'I would like water, thank you.' },
    { native: '你叫什么名字？', romanization: 'nǐ jiào shénme míngzi', english: 'What is your name?' },
    { native: '你好吗？', romanization: 'nǐ hǎo ma', english: 'How are you?' },
    { native: '我很好。', romanization: 'wǒ hěn hǎo', english: 'I am fine.' },
    { native: '是。', romanization: 'shì', english: 'Yes.' },
    { native: '不是。', romanization: 'bú shì', english: 'No.' },
    { native: '请说慢一点。', romanization: 'qǐng shuō màn yìdiǎn', english: 'Please speak slowly.' },
    { native: '谢谢！', romanization: 'xièxie', english: 'Thank you!' },
    { native: '再见！', romanization: 'zàijiàn', english: 'Goodbye!' },
  ],
  ja: [
    { native: 'こんにちは！', romanization: 'konnichiwa', english: 'Hello!' },
    { native: '私の名前は___です。', romanization: 'watashi no namae wa ___ desu', english: 'My name is ___.' },
    { native: 'お水をください。', romanization: 'omizu o kudasai', english: 'Water, please.' },
    { native: 'お名前は何ですか？', romanization: 'onamae wa nan desu ka', english: 'What is your name?' },
    { native: 'お元気ですか？', romanization: 'ogenki desu ka', english: 'How are you?' },
    { native: '元気です。', romanization: 'genki desu', english: 'I am fine.' },
    { native: 'はい。', romanization: 'hai', english: 'Yes.' },
    { native: 'いいえ。', romanization: 'iie', english: 'No.' },
    { native: 'ゆっくり話してください。', romanization: 'yukkuri hanashite kudasai', english: 'Please speak slowly.' },
    { native: 'ありがとうございます！', romanization: 'arigatō gozaimasu', english: 'Thank you!' },
    { native: 'さようなら！', romanization: 'sayōnara', english: 'Goodbye!' },
  ],
  ko: [
    { native: '안녕하세요!', romanization: 'annyeonghaseyo', english: 'Hello!' },
    { native: '제 이름은 ___예요.', romanization: 'je ireumeun ___yeyo', english: 'My name is ___.' },
    { native: '물 주세요.', romanization: 'mul juseyo', english: 'Water, please.' },
    { native: '이름이 뭐예요?', romanization: 'ireumi mwoyeyo', english: 'What is your name?' },
    { native: '어떻게 지내세요?', romanization: 'eotteoke jinaeseyo', english: 'How are you?' },
    { native: '잘 지내요.', romanization: 'jal jinaeyo', english: 'I am fine.' },
    { native: '네.', romanization: 'ne', english: 'Yes.' },
    { native: '아니요.', romanization: 'aniyo', english: 'No.' },
    { native: '천천히 말해 주세요.', romanization: 'cheoncheonhi malhae juseyo', english: 'Please speak slowly.' },
    { native: '감사합니다!', romanization: 'gamsahamnida', english: 'Thank you!' },
    { native: '안녕히 가세요!', romanization: 'annyeonghi gaseyo', english: 'Goodbye!' },
  ],
  kn: [
    { native: 'ನಮಸ್ಕಾರ!', romanization: 'namaskāra', english: 'Hello!' },
    { native: 'ನನ್ನ ಹೆಸರು ___.', romanization: 'nanna hesaru ___', english: 'My name is ___.' },
    { native: 'ನನಗೆ ನೀರು ಬೇಕು.', romanization: 'nanage nīru bēku', english: 'I would like water.' },
    { native: 'ನಿಮ್ಮ ಹೆಸರೇನು?', romanization: 'nimma hesarēnu', english: 'What is your name?' },
    { native: 'ಹೇಗಿದ್ದೀರಿ?', romanization: 'hēgiddīri', english: 'How are you?' },
    { native: 'ನಾನು ಚೆನ್ನಾಗಿದ್ದೇನೆ.', romanization: 'nānu chennāgiddēne', english: 'I am fine.' },
    { native: 'ಹೌದು.', romanization: 'haudu', english: 'Yes.' },
    { native: 'ಇಲ್ಲ.', romanization: 'illa', english: 'No.' },
    { native: 'ದಯವಿಟ್ಟು ನಿಧಾನವಾಗಿ ಮಾತನಾಡಿ.', romanization: 'dayaviṭṭu nidhānavāgi mātanāḍi', english: 'Please speak slowly.' },
    { native: 'ಧನ್ಯವಾದಗಳು!', romanization: 'dhanyavādagaḷu', english: 'Thank you!' },
    { native: 'ಮತ್ತೆ ಸಿಗೋಣ!', romanization: 'matte sigōṇa', english: 'See you again!' },
  ],
  pa: [
    { native: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ!', romanization: 'sat srī akāl', english: 'Hello!' },
    { native: 'ਮੇਰਾ ਨਾਮ ___ ਹੈ।', romanization: 'merā nām ___ hai', english: 'My name is ___.' },
    { native: 'ਮੈਨੂੰ ਪਾਣੀ ਚਾਹੀਦਾ ਹੈ।', romanization: 'mainū̃ pāṇī chāhīdā hai', english: 'I would like water.' },
    { native: 'ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ?', romanization: 'tuhāḍā nām kī hai', english: 'What is your name?' },
    { native: 'ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?', romanization: 'tusī̃ kivē̃ ho', english: 'How are you?' },
    { native: 'ਮੈਂ ਠੀਕ ਹਾਂ।', romanization: 'maĩ ṭhīk hā̃', english: 'I am fine.' },
    { native: 'ਹਾਂ।', romanization: 'hā̃', english: 'Yes.' },
    { native: 'ਨਹੀਂ।', romanization: 'nahī̃', english: 'No.' },
    { native: 'ਕਿਰਪਾ ਕਰਕੇ ਹੌਲੀ ਬੋਲੋ।', romanization: 'kirpā karkē haulī bolo', english: 'Please speak slowly.' },
    { native: 'ਧੰਨਵਾਦ!', romanization: 'dhannavād', english: 'Thank you!' },
    { native: 'ਫਿਰ ਮਿਲਾਂਗੇ!', romanization: 'phir milā̃gē', english: 'See you again!' },
  ],
  gu: [
    { native: 'નમસ્તે!', romanization: 'namaste', english: 'Hello!' },
    { native: 'મારું નામ ___ છે.', romanization: 'māruṁ nām ___ che', english: 'My name is ___.' },
    { native: 'મને પાણી જોઈએ છે.', romanization: 'mane pāṇī joīe che', english: 'I would like water.' },
    { native: 'તમારું નામ શું છે?', romanization: 'tamāruṁ nām śuṁ che', english: 'What is your name?' },
    { native: 'તમે કેમ છો?', romanization: 'tame kem cho', english: 'How are you?' },
    { native: 'હું મજામાં છું.', romanization: 'huṁ majāmāṁ chuṁ', english: 'I am fine.' },
    { native: 'હા.', romanization: 'hā', english: 'Yes.' },
    { native: 'ના.', romanization: 'nā', english: 'No.' },
    { native: 'કૃપા કરીને ધીમે બોલો.', romanization: 'kṛpā karīne dhīme bolo', english: 'Please speak slowly.' },
    { native: 'આભાર!', romanization: 'ābhār', english: 'Thank you!' },
    { native: 'ફરી મળીશું!', romanization: 'pharī maḷīśuṁ', english: 'See you again!' },
  ],
  te: [
    { native: 'నమస్కారం!', romanization: 'namaskāram', english: 'Hello!' },
    { native: 'నా పేరు ___.', romanization: 'nā pēru ___', english: 'My name is ___.' },
    { native: 'నాకు నీళ్లు కావాలి.', romanization: 'nāku nīḷlu kāvāli', english: 'I would like water.' },
    { native: 'మీ పేరు ఏమిటి?', romanization: 'mī pēru ēmiṭi', english: 'What is your name?' },
    { native: 'మీరు ఎలా ఉన్నారు?', romanization: 'mīru elā unnāru', english: 'How are you?' },
    { native: 'నేను బాగున్నాను.', romanization: 'nēnu bāgunnānu', english: 'I am fine.' },
    { native: 'అవును.', romanization: 'avunu', english: 'Yes.' },
    { native: 'కాదు.', romanization: 'kādu', english: 'No.' },
    { native: 'దయచేసి నెమ్మదిగా మాట్లాడండి.', romanization: 'dayacēsi nemmadigā māṭlāḍaṇḍi', english: 'Please speak slowly.' },
    { native: 'ధన్యవాదాలు!', romanization: 'dhanyavādālu', english: 'Thank you!' },
    { native: 'మళ్లీ కలుద్దాం!', romanization: 'maḷlī kaluddāṁ', english: 'See you again!' },
  ],
  sa: [
    { native: 'नमस्ते!', romanization: 'namaste', english: 'Hello!' },
    { native: 'मम नाम ___ अस्ति।', romanization: 'mama nāma ___ asti', english: 'My name is ___.' },
    { native: 'मह्यं जलं देहि।', romanization: 'mahyaṁ jalaṁ dehi', english: 'Please give me water.' },
    { native: 'तव नाम किम्?', romanization: 'tava nāma kim', english: 'What is your name?' },
    { native: 'त्वं कथम् असि?', romanization: 'tvaṁ katham asi', english: 'How are you?' },
    { native: 'अहं कुशली अस्मि।', romanization: 'ahaṁ kuśalī asmi', english: 'I am fine.' },
    { native: 'आम्।', romanization: 'ām', english: 'Yes.' },
    { native: 'न।', romanization: 'na', english: 'No.' },
    { native: 'कृपया शनैः वद।', romanization: 'kṛpayā śanaiḥ vada', english: 'Please speak slowly.' },
    { native: 'धन्यवादः!', romanization: 'dhanyavādaḥ', english: 'Thank you!' },
    { native: 'पुनर्मिलामः!', romanization: 'punarmilāmaḥ', english: 'See you again!' },
  ],
};
