import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { getCourse } from '../src/content/course-catalog';
import { phrasebook } from '../src/content/phrasebook';

type Variant = { locale: 'en-US' | 'en-GB'; voice: string };
type Clip = { file: string; text: string };
type Manifest = Record<string, { generatedAt: string; model: string; text: string; voice: string }>;

const execFileAsync = promisify(execFile);
const root = process.cwd();
const audioRoot = path.join(root, 'assets', 'audio');
const manifestPath = path.join(audioRoot, '.english-content-generated.json');
const generatedModulePath = path.join(root, 'src', 'content', 'english-content-audio.generated.ts');
const variants: Variant[] = [
  { locale: 'en-US', voice: 'en-US-AvaNeural' },
  { locale: 'en-GB', voice: 'en-GB-SoniaNeural' },
];
const course = getCourse('en');
if (!course) throw new Error('English course is missing');
const contentClips: Clip[] = [
  ...(phrasebook.en ?? []).map((phrase, index) => ({ file: `en-phrase-${index + 1}.mp3`, text: phrase.native })),
  ...course.vocabulary.map((entry) => ({ file: `en-vocabulary-${entry.concept}.mp3`, text: entry.native })),
];
const jobs = variants.flatMap((variant) => contentClips.map((clip) => ({ variant, clip })));
const wait = (milliseconds: number) => new Promise((resolve) => setTimeout(resolve, milliseconds));

async function readManifest(): Promise<Manifest> {
  try { return JSON.parse(await fs.readFile(manifestPath, 'utf8')) as Manifest; } catch { return {}; }
}

async function exists(filePath: string) {
  try { await fs.access(filePath); return true; } catch { return false; }
}

async function validMp3(filePath: string) {
  const data = await fs.readFile(filePath);
  const id3 = data.toString('ascii', 0, 3) === 'ID3';
  const sync = data[0] === 0xff && (data[1] & 0xe0) === 0xe0;
  if (data.length < 1_024 || (!id3 && !sync)) throw new Error('invalid MP3');
}

async function generate(variant: Variant, clip: Clip, attempt = 1): Promise<void> {
  const directory = path.join(audioRoot, variant.locale);
  const filePath = path.join(directory, clip.file);
  await fs.mkdir(directory, { recursive: true });
  try {
    await execFileAsync('python', [
      '-m', 'edge_tts', '--voice', variant.voice, '--rate=-8%', '--pitch=+0Hz',
      '--text', clip.text.replace(/_{2,}/g, ','), '--write-media', filePath,
    ], { windowsHide: true, timeout: 90_000 });
    await validMp3(filePath);
  } catch (error) {
    await fs.rm(filePath, { force: true });
    if (attempt < 5) { await wait(2_000 * attempt); return generate(variant, clip, attempt + 1); }
    throw error;
  }
}

async function writeModule(manifest: Manifest) {
  const lines: string[] = [];
  let count = 0;
  for (const { variant, clip } of jobs) {
    const key = `${variant.locale}/${clip.file}`;
    if (!manifest[key] || !await exists(path.join(audioRoot, key))) continue;
    lines.push(`  ${JSON.stringify(`${variant.locale}:${clip.text.trim()}`)}: require('../../assets/audio/${key}'),`);
    count += 1;
  }
  const source = `import type { AudioSource } from 'expo-audio';\n\n// Generated by scripts/generate-english-content-audio.ts. Do not edit by hand.\nconst contentAudio: Record<string, AudioSource> = {\n${lines.join('\n')}\n};\n\nexport function getEnglishContentAudio(text: string, pronunciationVariantId: string): AudioSource | null {\n  return contentAudio[\`\${pronunciationVariantId}:\${text.trim()}\`] ?? null;\n}\n\nexport const englishContentRecordingCount = ${count};\n`;
  await fs.writeFile(generatedModulePath, source);
  return count;
}

async function main() {
  const manifest = await readManifest();
  const pending = [];
  for (const job of jobs) {
    const key = `${job.variant.locale}/${job.clip.file}`;
    if (!manifest[key] || !await exists(path.join(audioRoot, key))) pending.push(job);
  }
  console.log(`English content pack: ${jobs.length - pending.length}/${jobs.length} ready.`);
  if (process.argv.includes('--plan')) {
    await writeModule(manifest);
    return;
  }
  for (let offset = 0; offset < pending.length; offset += 6) {
    const batch = pending.slice(offset, offset + 6);
    await Promise.all(batch.map(({ variant, clip }) => generate(variant, clip)));
    for (const { variant, clip } of batch) manifest[`${variant.locale}/${clip.file}`] = {
      generatedAt: new Date().toISOString(), model: 'edge-neural-tts', text: clip.text, voice: variant.voice,
    };
    await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
    console.log(`Generated ${Math.min(offset + batch.length, pending.length)}/${pending.length}`);
  }
  console.log(`Finished. ${await writeModule(manifest)}/${jobs.length} English content recordings are mapped.`);
}

main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
